export const errorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  USER_EXISTS: 'USER_EXISTS',

  PAGE_WATCHER_INVALID_TICKET: 'PAGE_WATCHER_INVALID_TICKET',
  PAGE_WATCHER_TRIED: 'PAGE_WATCHER_TRIED',
};
